name: Rebar CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  mac:
    uses: ./.github/workflows/rebar.yml
    with:
      runs-on: macOS-13
    secrets: inherit
  linux:
    uses: ./.github/workflows/rebar.yml
    with:
      runs-on: ubuntu-latest
    secrets: inherit
