name: Rebar CI
on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
permissions:
  contents: read
concurrency:
  group: std-${{ github.workflow }}-${{ github.ref }}-${{ inputs.runs-on }}
  cancel-in-progress: true
jobs:
  discover:
    outputs:
      hits: ${{ steps.discovery.outputs.hits }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v25
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: divnix/std-action/discover@main
        id: discovery
  shells:
    needs: discover
    name: ${{ matrix.target.jobName }}
    runs-on: ${{ inputs.runs-on }}
    if: fromJSON(needs.discover.outputs.hits).devshells.build != '{}'
    strategy:
      matrix:
        target: ${{ fromJSON(needs.discover.outputs.hits).devshells.build }}
    steps:
      - uses: nixbuild/nix-quick-install-action@v25
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: divnix/std-action/run@main
  tests:
    needs: discover
    name: ${{ matrix.target.jobName }}
    runs-on: ${{ inputs.runs-on }}
    if: fromJSON(needs.discover.outputs.hits).snapshots.check != '{}'
    strategy:
      matrix:
        target: ${{ fromJSON(needs.discover.outputs.hits).snapshots.check }}
    steps:
      - uses: nixbuild/nix-quick-install-action@v25
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: divnix/std-action/run@main
